// VoiceGallery.jsx — two zones:
//   • Archetypes — a browsable library of *designed* voices (no real people),
//     generated by VoiceStudio's own voice-design engine. Featured cards up top,
//     facet filters to explore hundreds. (core.archetypes / /archetypes API)
//   • My Imports — a neutral importer: paste any URL you have the rights to, or
//     upload a file, trim it, save it. The project ships no celebrity catalog.
import React, { useCallback, useEffect, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Sparkles, Store, Upload, LibraryBig } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger } from '../components/ui/tabs';
import { archetypePreviewUrl, useArchetypeAsProfile } from '../api/archetypes';
import { addCommunityItem, communityPreviewUrl } from '../api/community';
import { previewVoiceUrl } from '../api/gallery';
import { useAppStore } from '../store';
import { apiFetch } from '../api/client';
import { playBlobAudio } from '../utils/media';
import { stopActivePlayback } from '../utils/playback';
import { nextCastColor } from '../utils/storyCast';
import { instructToVdStates } from '../utils/voiceInstruct';
import ArchetypesZone from '../components/gallery/ArchetypesZone';
import CommunityZone from '../components/gallery/CommunityZone';
import ImportsZone from '../components/gallery/ImportsZone';

const NOOP = () => {};

export default function VoiceGallery({ clearSelectedProfile = NOOP }) {
  const { t } = useTranslation();

  const zone = useAppStore((s) => s.galleryZone);
  const setZone = useAppStore((s) => s.setGalleryZone);
  const filters = useAppStore((s) => s.archetypeFilters);
  const setFilter = useAppStore((s) => s.setArchetypeFilter);
  const resetFilters = useAppStore((s) => s.resetArchetypeFilters);
  const favorites = useAppStore((s) => s.favoriteArchetypeIds);
  const toggleFavorite = useAppStore((s) => s.toggleFavoriteArchetype);
  const viewMode = useAppStore((s) => s.galleryViewMode);
  const setViewMode = useAppStore((s) => s.setGalleryViewMode);
  const setMode = useAppStore((s) => s.setMode);
  const setDefineMethod = useAppStore((s) => s.setDefineMethod);
  const setPendingProfileId = useAppStore((s) => s.setPendingProfileId);
  const setInstruct = useAppStore((s) => s.setInstruct);
  const setVdStates = useAppStore((s) => s.setVdStates);
  const setLanguage = useAppStore((s) => s.setLanguage);
  const upsertCastMember = useAppStore((s) => s.upsertCastMember);
  const setOutputPrefs = useAppStore((s) => s.setOutputPrefs);
  const convertMode = useAppStore((s) => s.convertMode);

  const [playingId, setPlayingId] = useState(null);
  const [loadingPreviewId, setLoadingPreviewId] = useState(null);
  const [materializingId, setMaterializingId] = useState(null);
  const [notice, setNotice] = useState(null);
  const noticeTimer = useRef(null);
  const materializingRef = useRef(false);
  // Stale-async guards: gallery operations can outlive their trigger — a
  // preview fetch resolving after the page unmounted, a decode-error retry
  // firing after the user picked another voice, or a save-as-profile finishing
  // after the user left (which would redirect them into a workspace they had
  // already navigated away from). Each async operation captures the current
  // generation token and re-checks it before playback, navigation, and every
  // setState; unmount and each newer operation of the same kind invalidate it.
  const previewSeq = useRef(0);
  const materializeSeq = useRef(0);

  const flash = useCallback((msg) => {
    setNotice(msg);
    if (noticeTimer.current) window.clearTimeout(noticeTimer.current);
    noticeTimer.current = window.setTimeout(() => setNotice(null), 3500);
  }, []);

  useEffect(
    () => () => {
      previewSeq.current += 1;
      materializeSeq.current += 1;
      if (noticeTimer.current) window.clearTimeout(noticeTimer.current);
    },
    [],
  );

  // Fetch a preview clip and play it through the shared playback path
  // (playBlobAudio handles the Tauri "blob: URLs are dead in media elements"
  // detour — this page used to carry its own copy of that logic). The claim
  // routes to the global mini-player with the voice name as its label, and
  // starting any other playback stops this one (#316).
  const playUrl = useCallback(
    async (url, id, label, fallbackUrl = null) => {
      if (playingId === id) {
        stopActivePlayback(); // onDone('stopped') below resets playingId
        return;
      }
      const gen = ++previewSeq.current;
      const stale = () => previewSeq.current !== gen;
      setLoadingPreviewId(id);
      try {
        // no-store: preview audio is re-rendered server-side when an archetype is
        // fixed/changed, but the URL is stable. Without this the WebView's HTTP
        // cache replays the first clip it ever fetched (a stale render) forever.
        const resp = await apiFetch(url, { cache: 'no-store' });
        const blob = await resp.blob();
        if (stale()) return;
        setPlayingId(id);
        await playBlobAudio(blob, {
          label,
          // A present, verified gallery file can still be undecodable. The media
          // element reports that asynchronously, so retry from the backend's
          // explicit local-render path here rather than leaving a silent card.
          onDone: (reason) => {
            if (stale()) return;
            setPlayingId((cur) => (cur === id ? null : cur));
            if (reason === 'error' && fallbackUrl) {
              void playUrl(fallbackUrl, id, label);
            }
          },
        });
      } catch (e) {
        if (stale()) return;
        setPlayingId((cur) => (cur === id ? null : cur));
        flash(
          t('gallery.preview_failed', {
            message: e?.message || String(e),
            defaultValue: 'Preview unavailable: {{message}}',
          }),
        );
      } finally {
        if (!stale()) setLoadingPreviewId(null);
      }
    },
    [flash, playingId, t],
  );

  const openDesigner = useCallback(
    (item) => {
      clearSelectedProfile();
      setPendingProfileId(null);
      setVdStates(instructToVdStates(item.instruct || ''));
      setInstruct('');
      setLanguage(item.language || 'Auto');
      setDefineMethod('design');
      setMode('studio');
    },
    [
      clearSelectedProfile,
      setDefineMethod,
      setInstruct,
      setLanguage,
      setMode,
      setPendingProfileId,
      setVdStates,
    ],
  );

  const placeProfile = useCallback(
    (profile, target = 'studio') => {
      if (target === 'studio') {
        clearSelectedProfile();
        setPendingProfileId(profile.profile_id);
        setMode('studio');
        return;
      }
      if (target === 'stories') {
        const cast = useAppStore.getState().cast || [];
        if (!cast.some((member) => member.profileId === profile.profile_id)) {
          upsertCastMember({
            id: `voice_${profile.profile_id}`,
            name: profile.name,
            color: nextCastColor(cast),
            profileId: profile.profile_id,
          });
        }
        convertMode('stories');
        setMode('stories');
        return;
      }
      setOutputPrefs({ defaultVoice: profile.profile_id });
      convertMode('audiobook');
      setMode('audiobook');
    },
    [
      clearSelectedProfile,
      convertMode,
      setMode,
      setOutputPrefs,
      setPendingProfileId,
      upsertCastMember,
    ],
  );

  const materialize = useCallback(
    async (item, createProfile, target) => {
      // A ref closes the double-click window before React can paint `disabled`.
      if (materializingRef.current) return;
      materializingRef.current = true;
      const gen = ++materializeSeq.current;
      const stale = () => materializeSeq.current !== gen;
      setMaterializingId(item.id);
      try {
        const profile = await createProfile(item.id, item.name);
        if (stale()) return;
        placeProfile(profile, target);
      } catch (e) {
        if (stale()) return;
        flash(
          t('gallery.use_failed', {
            message: e?.message || String(e),
            defaultValue: 'Could not create that voice: {{message}}',
          }),
        );
      } finally {
        materializingRef.current = false;
        if (!stale()) setMaterializingId(null);
      }
    },
    [flash, placeProfile, t],
  );

  const communityPlaybackId = (item) =>
    `community:${item._source_repo || item.source || 'default'}:${item.id}`;

  const zoneItems = [
    {
      value: 'archetypes',
      Icon: Sparkles,
      label: t('gallery.zone_archetypes', { defaultValue: 'Archetypes' }),
    },
    {
      value: 'community',
      Icon: Store,
      label: t('gallery.zone_community', { defaultValue: 'Community' }),
    },
    {
      value: 'imports',
      Icon: Upload,
      label: t('gallery.zone_imports', { defaultValue: 'My Imports' }),
    },
  ];

  return (
    <div
      data-testid="voice-gallery"
      className="gallery flex h-full min-h-0 flex-col gap-[10px] overflow-hidden px-[20px] pb-[14px] pt-[16px] [container-type:inline-size] [container-name:gallery] @max-[640px]/gallery:px-[12px]"
    >
      <header className="flex shrink-0 flex-wrap items-end justify-between gap-x-[24px] gap-y-[12px]">
        <div className="flex min-w-0 items-center gap-[12px]">
          <span
            className="inline-flex h-[34px] w-[34px] shrink-0 items-center justify-center rounded-[12px] bg-[color-mix(in_srgb,#fabd2f_11%,transparent)] text-[#fabd2f]"
            aria-hidden="true"
          >
            <LibraryBig size={17} strokeWidth={1.6} />
          </span>
          <div className="min-w-0">
            <h2 className="m-0 truncate [font-family:var(--font-serif)] text-[1.5rem] font-normal leading-tight tracking-[-0.02em] text-[color:var(--chrome-fg)]">
              {t('gallery.title', { defaultValue: 'VoiceStudio Gallery' })}
            </h2>
            <p className="m-0 mt-[2px] truncate text-[0.72rem] text-[color:var(--chrome-fg-muted)]">
              {t('gallery.subtitle', {
                defaultValue: 'Hundreds of ready-made designed voices — pick one and go.',
              })}
            </p>
          </div>
        </div>
        <Tabs value={zone} onValueChange={setZone} activationMode="manual" className="gap-0">
          <TabsList
            aria-label={t('gallery.title', { defaultValue: 'VoiceStudio Gallery' })}
            className="grid h-auto w-auto grid-cols-3 gap-[3px] rounded-[var(--chrome-radius-pill)] border border-transparent bg-[var(--chrome-bg)] p-[3px]"
          >
            {zoneItems.map(({ value, Icon, label }) => (
              <TabsTrigger
                key={value}
                value={value}
                data-gallery-zone={value}
                className="h-auto min-h-9 min-w-0 cursor-pointer whitespace-nowrap rounded-[var(--chrome-radius-pill)] border border-transparent bg-transparent px-3 py-[6px] text-[0.72rem] font-medium text-[color:var(--chrome-fg-muted)] transition-colors data-[state=active]:border-[var(--chrome-accent-border)] data-[state=active]:bg-[var(--chrome-accent-bg)] data-[state=active]:font-semibold data-[state=active]:text-[color:var(--chrome-accent)] data-[state=active]:shadow-none dark:data-[state=active]:border-[var(--chrome-accent-border)] dark:data-[state=active]:bg-[var(--chrome-accent-bg)] dark:data-[state=active]:text-[color:var(--chrome-accent)] hover:data-[state=inactive]:bg-[var(--chrome-hover-bg)]"
              >
                <Icon size={14} aria-hidden="true" />
                {label}
              </TabsTrigger>
            ))}
          </TabsList>
        </Tabs>
      </header>
      <div
        className="h-px shrink-0 [background-image:linear-gradient(90deg,color-mix(in_srgb,var(--chrome-fg)_12%,transparent),transparent_70%)]"
        aria-hidden="true"
      />

      {notice && (
        <div className="shrink-0 rounded-[var(--chrome-radius-pill)] bg-[color-mix(in_srgb,var(--chrome-accent)_9%,transparent)] px-[14px] py-[7px] text-[0.75rem] text-[color:var(--chrome-fg)]">
          {notice}
        </div>
      )}

      {zone === 'archetypes' ? (
        <ArchetypesZone
          t={t}
          filters={filters}
          setFilter={setFilter}
          resetFilters={resetFilters}
          favorites={favorites}
          toggleFavorite={toggleFavorite}
          viewMode={viewMode}
          setViewMode={setViewMode}
          playingId={playingId}
          loadingPreviewId={loadingPreviewId}
          onPreview={(a) =>
            playUrl(archetypePreviewUrl(a.id), a.id, a.name, archetypePreviewUrl(a.id, true))
          }
          onUse={(a) => materialize(a, useArchetypeAsProfile, 'studio')}
          onUseInStories={(a) => materialize(a, useArchetypeAsProfile, 'stories')}
          onUseAsAudiobookDefault={(a) => materialize(a, useArchetypeAsProfile, 'audiobook')}
          onDesign={openDesigner}
          materializingId={materializingId}
        />
      ) : zone === 'community' ? (
        <CommunityZone
          t={t}
          playingId={playingId}
          loadingPreviewId={loadingPreviewId}
          favorites={favorites}
          toggleFavorite={toggleFavorite}
          onPreview={(item) =>
            playUrl(
              communityPreviewUrl(item.id),
              communityPlaybackId(item),
              item.name,
              item.type === 'preset' ? communityPreviewUrl(item.id, true) : null,
            )
          }
          flash={flash}
          onDesign={openDesigner}
          onUse={(item) => materialize(item, addCommunityItem, 'studio')}
          onUseInStories={(item) => materialize(item, addCommunityItem, 'stories')}
          onUseAsAudiobookDefault={(item) => materialize(item, addCommunityItem, 'audiobook')}
          materializingId={materializingId}
        />
      ) : (
        <ImportsZone
          t={t}
          playingId={playingId}
          loadingPreviewId={loadingPreviewId}
          onPlayGallery={(v) => playUrl(previewVoiceUrl(v.id), v.id, v.name)}
          onUseProfile={placeProfile}
          flash={flash}
        />
      )}
    </div>
  );
}
